image: node:latest

stages: 
  - install
  - validation
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: install
  script: 
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: validation
  dependencies:
    - install
  script: 
    - npm run lint

format:
  stage: validation
  dependencies:
    - install
  script: 
    - npx prettier --write .

jest:
  stage: validation
  dependencies:
    - install
  script:
    - npm test


build-job:
  stage: build
  script:
    - npm run build
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main' 
      when: on_success
      allow_failure: true
  artifacts:
    paths:
      - out/

deploy:
  stage: deploy
  dependencies: 
    - build
  script:
    -  npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main' 
      when: on_success
      allow_failure: true
