version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:16

    steps:
      - checkout

      - run:
          name: Install npm dependencies
          command: npm install

      - run:
          name: run lint
          command: npm run lint

      - run:
          name: run prettier
          command: npm run prettier

      - run:
          name: run jest
          command: npm test

      - run:
          name: build
          command: npm run build
          

      - run:
          name: deploy
          command: npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

workflows: #run order
  test_build_deploy:
    jobs:
      - run_tests
      
  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                  - main
    jobs:
      - run_tests
